spring:
    datasource:
        url : jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=UTF-8
        username : root
        password : root
        driver-class-name : com.mysql.jdbc.Driver
    jpa:
        database : MYSQL
        show-sql : true
        hibernate:  
            ddl-auto : update
        properties:
            hibernate:
                dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        time-zone : GMT+8
        date-format : yyyy-MM-dd HH:mm:ss

logging:
    file : log.log
    level :
        com.plumdo.flow.config.DruidConfiguration : debug
        com.alibaba.druid : debug
        druid.sql.DruidDataSource : debug
        com.alibaba.druid.pool.Connection : debug,stdout
        com.alibaba.druid.pool.Statement : debug,stdout
        com.alibaba.druid.pool.ResultSet : debug,stdout
    
    
server:
    port : 8082
    
           