flowable:
  databaseSchemaUpdate : true #create-drop create false
  cmmn.enabled : false
  dmn.enabled : false
  form.enabled : false
  databaseSchema : plumdo_flow

logging:
  name: flow-service
    
---

#生产环境
spring.profiles: service-pro
  
  
---

#开发环境
spring.profiles: service-dev
  
server:
  port : 8082

  